//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Employee = newEmployeeTable("", "employee", "")

type employeeTable struct {
	sqlite.Table

	//Columns
	ID          sqlite.ColumnInteger
	FirstName   sqlite.ColumnString
	LastName    sqlite.ColumnString
	BirthDate   sqlite.ColumnString
	StartDate   sqlite.ColumnString
	Salary      sqlite.ColumnFloat
	PvdFundRate sqlite.ColumnFloat

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type EmployeeTable struct {
	employeeTable

	EXCLUDED employeeTable
}

// AS creates new EmployeeTable with assigned alias
func (a EmployeeTable) AS(alias string) *EmployeeTable {
	return newEmployeeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmployeeTable with assigned schema name
func (a EmployeeTable) FromSchema(schemaName string) *EmployeeTable {
	return newEmployeeTable(schemaName, a.TableName(), a.Alias())
}

func newEmployeeTable(schemaName, tableName, alias string) *EmployeeTable {
	return &EmployeeTable{
		employeeTable: newEmployeeTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newEmployeeTableImpl("", "excluded", ""),
	}
}

func newEmployeeTableImpl(schemaName, tableName, alias string) employeeTable {
	var (
		IDColumn          = sqlite.IntegerColumn("id")
		FirstNameColumn   = sqlite.StringColumn("first_name")
		LastNameColumn    = sqlite.StringColumn("last_name")
		BirthDateColumn   = sqlite.StringColumn("birth_date")
		StartDateColumn   = sqlite.StringColumn("start_date")
		SalaryColumn      = sqlite.FloatColumn("salary")
		PvdFundRateColumn = sqlite.FloatColumn("pvd_fund_rate")
		allColumns        = sqlite.ColumnList{IDColumn, FirstNameColumn, LastNameColumn, BirthDateColumn, StartDateColumn, SalaryColumn, PvdFundRateColumn}
		mutableColumns    = sqlite.ColumnList{FirstNameColumn, LastNameColumn, BirthDateColumn, StartDateColumn, SalaryColumn, PvdFundRateColumn}
	)

	return employeeTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		FirstName:   FirstNameColumn,
		LastName:    LastNameColumn,
		BirthDate:   BirthDateColumn,
		StartDate:   StartDateColumn,
		Salary:      SalaryColumn,
		PvdFundRate: PvdFundRateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
