//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Employee struct {
	ID          int32 `sql:"primary_key"`
	FirstName   string
	LastName    string
	BirthDate   string
	StartDate   string
	Salary      float64
	PvdFundRate float64
}
